### ISSUE TITLE
Some characters are missing in generated output

### ISSUE THREAD

**Issue by abenhamdine** [SweetIQ/schemats#37] opened 2017-01-24 12:38 UTC
Nodejs : 7.4.0
Postgres : 9.6.1
schemats : 1.0.1

While using last version 1.0.1 of this module, I run into a strange bug : in the generated file, some characters are missing, always in the third line of first interface declaration.

Eg, in the following example, the file contains `export type sal_matriculetring;` instead of `export type sal_matricule = string;`
4 characters ` = s` are missing

Excerpt of output : 

```
/**
 * AUTO-GENERATED FILE @ 2017-01-24 13:27:02 - DO NOT EDIT!
 *
 * This file was generated with schemats node package:
 * $ schemats generate -c postgres://username:password@localhost:5432/testpayroll -t pay_salarie_sal -o schema.ts
 *
 * Re-run the command above.
 *
 */

    
export namespace pay_salarie_salFields {
    export type sal_id = number;
    export type sal_matriculetring;
```

With another table, the missing characters are in nearly the same place : 

```
/**
 * AUTO-GENERATED FILE @ 2017-01-24 13:33:18 - DO NOT EDIT!
 *
 * This file was generated with schemats node package:
 * $ schemats generate -c postgres://username:password@localhost:5432/testpayroll -t pay_contrat_cnt -o schema.ts
 *
 * Re-run the command above.
 *
 */

    
export namespace pay_contrat_cntFields {
    export type cnt_soldetc_mdp_id = number | null;
    exporte tex_id = number | null;
```
Of course, expected : `export type tex_id` instead of `exporte tex_id`
4 characters `typ` are missing

It's the only issue in the output file : all other lines are correct.

I don't reproduce the issue with osm artifact test file, which is weird.

**Comment by xiamx** [comment] 2017-01-24 14:37
I've also seen this before.. and it's frustrating. So far I believe the issue is either with the `fs.saveFile` function or `typescript-formatter`.

**Comment by abenhamdine** [comment] 2017-01-24 16:06
Thx for your quick answer and for the clue.
I will investigate when I have some time.

**Comment by xiamx** [comment] 2017-01-24 16:17
No problem. I've seen it happening for one day [[1]] but I'm unable to reproduce it now for some reason. 

[1]: https://circleci.com/gh/SweetIQ/schemats/144

**Comment by xiamx** [comment] 2017-01-24 16:48
Removed a potential culprit with https://github.com/SweetIQ/schemats/pull/38 .

**Comment by abenhamdine** [comment] 2017-01-25 09:28
Thanks !
But after have merged #38 locally, I still have the issue. No difference at all.

**Comment by xiamx** [comment] 2017-01-26 02:58
I will probably have to look into typescript-formatter then..

**Comment by vitaly-t** [comment] 2017-01-26 15:20
@xiamx how good are your tests? You don't really know that without code coverage. Check out - all my modules have it, you can use them as an example ;)

**Comment by xiamx** [comment] 2017-01-27 16:50
@vitaly-t tests are admittedly not comprehensive at the moment :joy: . We only have end to end tests as of now. I should start adding some unit tests

**Comment by Jujunol** [comment] 2017-02-03 21:57
I'm experiencing the same problem with `export type password = string` being generated as `expoype password = string`

**Comment by xiamx** [comment] 2017-02-03 22:04
I will take another look at this over the weekend

**Comment by vitaly-t** [comment] 2017-02-08 14:24
Anything? It's a killer bug, you know, very critical :wink:

**Comment by xiamx** [comment] 2017-02-08 14:34
@vitaly-t :joy: I can't reproduce it, neither locally nor on CI.. even though code coverage report by Istanbul is at 100% line covered

**Comment by xiamx** [comment] 2017-02-08 15:05
Bumping the version of typescript-formatter to 4.1.0. @abenhamdine @Jujunol can you guys please paste the content of your tsconfig.json and tslintrc (if any)? It should help me reproduce this bug locally.

**Comment by abenhamdine** [comment] 2017-02-08 15:14
Bug still present in 1.1.0 for me, unfortunately.
I reproduce every time with a schema with a single table 

Here's the dump of the db : 
[dump.txt](https://github.com/SweetIQ/schemats/files/761012/dump.txt)

And the output file : 

```ts

/**
 * AUTO-GENERATED FILE @ 2017-02-08 16:14:07 - DO NOT EDIT!
 *
 * This file was generated with schemats node package:
 * $ schemats generate -c postgres://username:password@localhost:5432/test_schemats_2 -o schema.ts -t cta_situationcompte_sco
 *
 * Re-run the command above.
 *
 */

    
export namespace cta_situationcompte_scoFields {
    export type sco_id = number;
    export type sco_t_debit = number;
    export type sco_total_credit = number;
    export type sco_nb_ecritures = number;
    export type pst_id = number;
    export type cpt_id = number;

}

export interface cta_situationcompte_sco {
    sco_id: cta_situationcompte_scoFields.sco_id;
    sco_total_debit: cta_situationcompte_scoFields.sco_total_debit;
    sco_total_credit: cta_situationcompte_scoFields.sco_total_credit;
    sco_nb_ecritures: cta_situationcompte_scoFields.sco_nb_ecritures;
    pst_id: cta_situationcompte_scoFields.pst_id;
    cpt_id: cta_situationcompte_scoFields.cpt_id;

}
```

**Comment by xiamx** [comment] 2017-02-08 16:09
@abenhamdine Thanks. This is very helpful in reproducing it.

I can confirm If I disable typescript-formatter, by replacing index.ts
```
    let formatterOption = {
        replace: false,
        verify: false,
        tsconfig: true,
        tslint: true,
        editorconfig: true,
        tsfmt: false
    }

    const processedResult = await processString('schema.ts', output, formatterOption)
    return processedResult.dest
```
with simply `return output`

The generated file will have `export type sco_total_debit = number;` generated correctly. This is a weird issue and certainly suggests a bug in typescript-formatter (or a misusage of it in my part.) We use typescript-formatter to (mainly) generate files with correct indentation levels specified by the project's tslintrc or editorconfig.

**Comment by xiamx** [comment] 2017-02-08 16:25
Maybe we can receive some help of its author @vvakame I've created an issue there https://github.com/vvakame/typescript-formatter/issues/74

**Comment by xiamx** [comment] 2017-02-08 16:29
Interestingly, by removing the comment header from the input, we the issue disappeared. So maybe the temporal solution is to feed only the output without header to typescript-formatter, and then add the header afterward.

**Comment by xiamx** [comment] 2017-02-08 18:37
After some lengthy debug on typescript-formatter, I proposed a fix here https://github.com/vvakame/typescript-formatter/pull/75. I'll release a fix for schemats quickly by pointing the typescript-fromatter version to our fork.

**Comment by abenhamdine** [comment] 2017-02-08 19:18
1.1.1 solved the pb for me. Thx a lot @xiamx  ! 💃 😄 🎉 
@Jujunol could you confirm if it's the case for you too ?

**Comment by xiamx** [comment] 2017-02-08 19:30
@abenhamdine awesome, glad to know it fixed it ! 

Let's keep this tracking issue open until patches are merged in the upstream typescript-formatter project.

**Comment by xiamx** [comment] 2017-02-10 17:27
Thank you everyone, the patch is merged to typescript-formatter. Closing this issue with the release v1.1.2

**Closed by xiamx** 2017-02-10 17:27 UTC
